---
abstract: 'Catalyst based application'
author:
  - ',,,'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GridM
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::REST: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::Runtime: 5.80017
  Catalyst::View::TT: 0
  Config::General: 0
  DBD:Pg: 0
  DBIx::Class::EncodedColumn: 0
  HTML::FormHandler: 0
  HTML::FormHandler::Model::DBIC: 0
  Moose: 0
  namespace::autoclean: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
